Add more job attributes
gran-software-solutions/rust-jobs pull request #8
Opened 2023-08-06 19:23 UTC by dodalovicgran

2023-08-06 22:03 UTC, dodalovicgran commented
@gglazewskigran Sorry for this big contribution.

2023-08-07 04:36 UTC, gglazewskigran requested changes
A great PR! We are moving forward. I wasn't expecting you to know advanced CSS!

I'd ask for little changes:
1. Naming - "client" is confusing.
2. JobDetails shouldn't use form fields.

2023-08-07 04:36 UTC, gglazewskigran commented on src/database.rs
> +        let clients = ["Sony", "Google", "Amazon"];
Definition of a client:
A person or organization using the services of a lawyer or other professional person or company.

I wouldn't use the word "client" as those entities are not clients in this context. Maybe an employer, a company, a recruiter?

2023-08-07 04:36 UTC, gglazewskigran commented on src/jobs/handlers.rs
> +    //db_mutex.lock().unwrap().add(Job::from(new_job));
please remove the comment

2023-08-07 04:36 UTC, gglazewskigran commented on static/root/css/style.css
> +    /* 7! */
Please remove the comments

2023-08-07 04:36 UTC, gglazewskigran commented on src/jobs/handlers.rs
>      Redirect::to("/").using_status_code(StatusCode::SEE_OTHER)
You can use as well:
`Redirect::to("/").see_other()`

2023-08-07 04:36 UTC, gglazewskigran commented on templates/job.stpl
> +        </fieldset>
This shouldn't be a form. Maybe a table or just some divs, but not a form.

2023-08-07 07:32 UTC, gglazewskigran approved these changes
:rocket:

2023-08-07 08:14 UTC, merged